### ISSUE TITLE
evite submeter .exe no repositorio

### ISSUE THREAD

**Issue by josecamata** [EduardaNunes/Caca-Palavras#1]
Crie um arquivo .gitignore e inclua s extensôes que devem ser ignorado no versionamento.

*.exe
*.o 
*.so

**Comment by EduardaNunes** [comment]
Ok, professor. Obrigada pela dica, não sabia que era um problema. Nunca mexi com gitignore mas irei dar uma olhada.

**Comment by EduardaNunes** [comment]
Achei que fosse mais difícil configurar o gitignore mas é realmente só escrever isso kk. Fiz errado da primeira vez mas agora concertei e já sei usar. Obrigada professor!
